    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Copy filebeat 
      copy:
        src: /home/nagornov/filebeat-7.9.3-amd64.deb
        dest: /home/nagornov/

    - name: Install filebeat
      apt:
        deb: /home/nagornov/filebeat-7.9.3-amd64.deb

    - name: Copy config file for filebeat
      copy:
        src: /home/nagornov/terraform/filebeat.yml
        dest: /etc/filebeat
        mode: 0600
        owner: root
        group: root

    - name: Systemctl daemon reload
      systemd:
        daemon_reload: true
        name: filebeat.service
        state: started



